### ISSUE TITLE
Inqury about sc_bifurc_figs

### ISSUE THREAD

**Issue by teruhironakajima** [Simfreed/sc_bifurc_figs#1]
Hi.
Now I am interested in analyzing the single-cell bifurcation analysis and am trying to follow your analysis with your released codes.

But I don't find some notebook such as  saddle_node.ipynb and neutrophil.ipynb, so may I ask you how to find it?
Thank you very much and I look forward to hearing from you.

Teru

**Comment by Simfreed** [comment]
Sorry about that! Just uploaded those two into the ipynb directory. Please let me know if there are more issues!
-Simon

**Comment by teruhironakajima** [comment]
Thank you very much for prompt response.
I will be in touch if I need any further question.
